version: "3.9"

services:
  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/client
    depends_on:
      - backend

    container_name: react-app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./:/app/server

    container_name: node-api
