version: "3.9"

services:
  #mongodb
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-db:/data/db

    container_name: mongodb

  #client
  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

    container_name: react-app

  #api
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - MONGODB_URL = ${MONGODB_URL}
      - ACCESS_TOKEN_SECRET = ${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET = ${REFRESH_TOKEN_SECRET}
    depends_on:
      - mongodb

    container_name: node-api

volumes:
  mongo-db: {}
